---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.alloy.name }}
  namespace: argocd
spec:
  project: default
  source:
    chart: {{ .Values.alloy.chartName }}
    repoURL: {{ .Values.alloy.chartURL }}
    targetRevision: {{ .Values.alloy.chartRevision }}
    helm:
      releaseName: {{ .Values.alloy.releaseName }}
      valuesObject:
        alloy:
          configMap:
            create: false
            name: alloy-config
            key: config.alloy
          envFrom:
            - secretRef:
                name: alloy-api-secret
  destination:
    name: in-cluster
    namespace: {{ .Values.alloy.namespace }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
