apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yke-main
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/yke-main
spec:
  project: default
  source:
    repoURL: https://github.com/yquansah/yke.git
    path: argocd/applications
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
